#!/bin/bash
root=$(dirname "$0")
sources=${root}/libs

# Step 1: create new nghttp3.nim file
rm -f nghttp3.nim
touch nghttp3.nim

# Step 2: add prelude
cat "${root}/prelude.nim" >> nghttp3.nim

# Step 3: add compile directive for all c files
for file in `ls "${sources}/nghttp3/lib"/*.c`; do
  echo "{.compile: \"$file\".}" >> nghttp3.nim
done
echo "{.compile: \"${sources}/nghttp3/lib/sfparse/sfparse.c\".}" >> nghttp3.nim

# Step 4: generate nghttp3 source and append it to nghttp3.nim
nimble install futhark@0.15.0 # futhark is required by generate nghttp3_source.nim
nim c --maxLoopIterationsVM:100000000 generate_nghttp3.nim
# removes absolute path prefix from comments "Generated based on"
sed -i 's/Generated based on.*\/nim-http3\/libs\//Generated based on \/nim-http3\/libs\//g' nghttp3_source.nim
cat "${root}/nghttp3_source.nim" >> nghttp3.nim
rm -f nghttp3_source.nim # remove autogenerated nghttp3_source.nim file


