name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: linux
            cpu: amd64
          - os: linux-gcc-14
            cpu: amd64
          - os: macos
            cpu: amd64
          - os: macos-14
            cpu: arm64
        nim:
          - ref: version-1-6
            memory_management: refc
          - ref: version-2-0
            memory_management: refc
        include:
          - platform:
              os: linux
            builder: ubuntu-22.04
            shell: bash
          - platform:
              os: linux-gcc-14
            builder: ubuntu-24.04
            shell: bash
          - platform:
              os: macos
            builder: macos-13
            shell: bash
          - platform:
              os: macos-14
            builder: macos-14
            shell: bash

    defaults:
      run:
        shell: ${{ matrix.shell }}

    name: '${{ matrix.platform.os }}-${{ matrix.platform.cpu }} (Nim ${{ matrix.nim.ref }})'
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Nim
        uses: "./.github/actions/install_nim"
        with:
          os: ${{ matrix.platform.os }}
          cpu: ${{ matrix.platform.cpu }}
          shell: ${{ matrix.shell }}
          nim_ref: ${{ matrix.nim.ref }}

      - name: Use gcc 14
        if : ${{ matrix.platform.os == 'linux-gcc-14'}}
        run: |
          # Add GCC-14 to alternatives
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 14

          # Set GCC-14 as the default
          sudo update-alternatives --set gcc /usr/bin/gcc-14

      - name: Install nim-nghttp3 dependencies (tooling)
        uses: ./.github/actions/install_dependencies
        with:
          os: ${{ matrix.platform.os }}

      - name: Install repository deps (nimble install)
        run: |
          nimble install

      - name: Run tests
        run: |
          nim --version
          nimble --version
          gcc --version

          NIMFLAGS="${NIMFLAGS} --mm:${{ matrix.nim.memory_management }}"
          nimble test --styleCheck:off --verbose --debug
